# Generated by Django 3.1.1 on 2020-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
